using System.Globalization;
using System.Text;

namespace Photo2PCB.Core;

/// <summary>
/// Serializes a <see cref="RasterDocument"/> to a black-on-white SVG. The canvas is
/// dimensioned in real-world millimetres (with a matching mm-unit viewBox) so the
/// output is directly usable for PCB etching / CAM. Each pen run becomes a stroked
/// line whose width equals the aperture diameter; round line-caps turn single-pixel
/// runs into filled circles of the aperture size.
/// </summary>
public static class SvgWriter
{
    private static readonly CultureInfo Inv = CultureInfo.InvariantCulture;

    public static string Write(RasterDocument doc)
    {
        var sb = new StringBuilder();
        string w = F(doc.CanvasWidthMm);
        string h = F(doc.CanvasHeightMm);

        sb.AppendLine("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>");
        sb.Append("<svg xmlns=\"http://www.w3.org/2000/svg\" version=\"1.1\" ")
          .Append($"width=\"{w}mm\" height=\"{h}mm\" ")
          .Append($"viewBox=\"0 0 {w} {h}\">\n");
        sb.AppendLine($"  <!-- Generated by Photo2PCB. Aperture {F(doc.MinApertureMm)}–{F(doc.MaxApertureMm)} mm, " +
                      $"{doc.LineCount} lines, pitch {F(doc.LinePitchMm)} mm, dark gap {F(doc.DarkGapMm)} mm" +
                      $"{(doc.DarkLinesOverlap ? " (overlapping)" : "")}, " +
                      $"{doc.Columns}x{doc.Rows} cells from {doc.SourceWidthPx}x{doc.SourceHeightPx}px. -->");

        // White background.
        sb.AppendLine($"  <rect x=\"0\" y=\"0\" width=\"{w}\" height=\"{h}\" fill=\"#ffffff\"/>");

        // Pen runs share the stroke colour and round caps; each carries its own width (the local aperture).
        sb.AppendLine("  <g fill=\"none\" stroke=\"#000000\" stroke-linecap=\"round\">");
        foreach (ScanLine line in doc.ScanLines)
        {
            string y = F(line.YMm);
            foreach (PenRun run in line.Runs)
            {
                sb.Append("    <line x1=\"").Append(F(run.XStartMm))
                  .Append("\" y1=\"").Append(y)
                  .Append("\" x2=\"").Append(F(run.XEndMm))
                  .Append("\" y2=\"").Append(y)
                  .Append("\" stroke-width=\"").Append(F(run.WidthMm)).Append("\"/>\n");
            }
        }
        sb.AppendLine("  </g>");
        sb.AppendLine("</svg>");
        return sb.ToString();
    }

    public static void WriteToFile(RasterDocument doc, string path)
        => File.WriteAllText(path, Write(doc));

    /// <summary>Format a millimetre value with stable, compact precision (3 decimals).</summary>
    private static string F(double mm) => Math.Round(mm, 3).ToString("0.###", Inv);
}
